CREATE TABLE IF NOT EXISTS walker( mcgillID INTEGER PRIMARY KEY, rating INTEGER, isWalksafe BOOLEAN, hasSchedule BOOLEAN);
CREATE TABLE IF NOT EXISTS student (mcgillID INTEGER PRIMARY KEY);
CREATE TABLE IF NOT EXISTS request (requestid INTEGER PRIMARY KEY); 